import { Router } from 'express';

const router: Router = Router();

// Master list of Indian States and prominent Cities
const INDIAN_LOCATIONS: Record<string, string[]> = {
  'Tamil Nadu': [
    'Chennai',
    'Coimbatore',
    'Madurai',
    'Tiruchirappalli (Trichy)',
    'Salem',
    'Tirunelveli',
    'Erode',
    'Vellore',
    'Thanjavur',
    'Dindigul',
    'Ranipet',
    'Kanchipuram',
    'Tiruppur',
    'Nagercoil',
    'Cuddalore',
  ],
  'Karnataka': [
    'Bangalore (Bengaluru)',
    'Mysore (Mysuru)',
    'Mangalore (Mangaluru)',
    'Hubli-Dharwad',
    'Belgaum (Belagavi)',
    'Davangere',
    'Bellary (Ballari)',
    'Gulbarga (Kalaburagi)',
    'Shimoga (Shivamogga)',
    'Tumkur (Tumakuru)',
    'Udupi',
  ],
  'Maharashtra': [
    'Mumbai',
    'Pune',
    'Nagpur',
    'Thane',
    'Nashik',
    'Kalyan-Dombivli',
    'Vasai-Virar',
    'Aurangabad (Chhatrapati Sambhajinagar)',
    'Navi Mumbai',
    'Solapur',
    'Kolhapur',
  ],
  'Telangana': [
    'Hyderabad',
    'Warangal',
    'Nizamabad',
    'Khammam',
    'Karimnagar',
    'Ramagundam',
    'Mahbubnagar',
  ],
  'Andhra Pradesh': [
    'Visakhapatnam',
    'Vijayawada',
    'Guntur',
    'Nellore',
    'Kurnool',
    'Rajahmundry',
    'Tirupati',
    'Kakinada',
    'Anantapur',
  ],
  'Kerala': [
    'Kochi (Cochin)',
    'Thiruvananthapuram (Trivandrum)',
    'Kozhikode (Calicut)',
    'Thrissur',
    'Kollam',
    'Palakkad',
    'Alappuzha',
    'Kannur',
    'Kottayam',
  ],
  'Delhi (NCR)': [
    'New Delhi',
    'Central Delhi',
    'South Delhi',
    'North Delhi',
    'Noida',
    'Gurgaon (Gurugram)',
    'Ghaziabad',
    'Faridabad',
  ],
  'Gujarat': [
    'Ahmedabad',
    'Surat',
    'Vadodara',
    'Rajkot',
    'Bhavnagar',
    'Jamnagar',
    'Gandhinagar',
    'Junagadh',
  ],
  'West Bengal': [
    'Kolkata',
    'Howrah',
    'Durgapur',
    'Asansol',
    'Siliguri',
    'Bardhaman',
    'Kharagpur',
  ],
  'Rajasthan': [
    'Jaipur',
    'Jodhpur',
    'Kota',
    'Bikaner',
    'Ajmer',
    'Udaipur',
    'Bhilwara',
    'Alwar',
  ],
  'Uttar Pradesh': [
    'Lucknow',
    'Kanpur',
    'Varanasi',
    'Agra',
    'Prayagraj (Allahabad)',
    'Meerut',
    'Bareilly',
    'Aligarh',
    'Moradabad',
    'Gorakhpur',
  ],
  'Punjab': [
    'Ludhiana',
    'Amritsar',
    'Jalandhar',
    'Patiala',
    'Bathinda',
    'Mohali',
    'Pathankot',
  ],
  'Haryana': [
    'Gurugram',
    'Faridabad',
    'Panipat',
    'Ambala',
    'Yamunanagar',
    'Rohtak',
    'Hisar',
    'Karnal',
    'Panchkula',
  ],
  'Madhya Pradesh': [
    'Indore',
    'Bhopal',
    'Jabalpur',
    'Gwalior',
    'Ujjain',
    'Sagar',
    'Dewas',
    'Satna',
  ],
  'Bihar': [
    'Patna',
    'Gaya',
    'Bhagalpur',
    'Muzaffarpur',
    'Purnia',
    'Darbhanga',
    'Bihar Sharif',
  ],
  'Odisha': [
    'Bhubaneswar',
    'Cuttack',
    'Rourkela',
    'Berhampur',
    'Sambalpur',
    'Puri',
    'Balasore',
  ],
  'Assam': [
    'Guwahati',
    'Silchar',
    'Dibrugarh',
    'Jorhat',
    'Nagaon',
    'Tinsukia',
    'Tezpur',
  ],
  'Jharkhand': [
    'Ranchi',
    'Jamshedpur',
    'Dhanbad',
    'Bokaro Steel City',
    'Deoghar',
    'Hazaribagh',
  ],
  'Chhattisgarh': [
    'Raipur',
    'Bhilai',
    'Bilaspur',
    'Korba',
    'Rajnandgaon',
    'Durg',
  ],
  'Goa': [
    'Panaji',
    'Margao',
    'Vasco da Gama',
    'Mapusa',
    'Ponda',
  ],
  'Uttarakhand': [
    'Dehradun',
    'Haridwar',
    'Roorkee',
    'Haldwani',
    'Rishikesh',
    'Nainital',
  ],
  'Himachal Pradesh': [
    'Shimla',
    'Dharamshala',
    'Mandi',
    'Solan',
    'Kullu',
    'Manali',
  ],
  'Jammu & Kashmir': [
    'Srinagar',
    'Jammu',
    'Anantnag',
    'Baramulla',
    'Kathua',
  ],
  'Chandigarh': [
    'Chandigarh',
  ],
  'Puducherry': [
    'Puducherry',
    'Karaikal',
    'Oulgaret',
  ],
};

const DEFAULT_LOCATION = {
  country: 'India',
  state: 'Tamil Nadu',
  city: 'Chennai',
  latitude: 13.0827,
  longitude: 80.2707,
};

// GET /api/v1/locations/india - common API to get states, cities and default location
router.get('/india', (req, res) => {
  res.status(200).json({
    country: 'India',
    defaultLocation: DEFAULT_LOCATION,
    states: Object.keys(INDIAN_LOCATIONS).sort(),
    stateCityMap: INDIAN_LOCATIONS,
  });
});

export default router;
